import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API requests
registerRoute(
	({ url }) => url.pathname.startsWith('/api'),
	new NetworkFirst({
		cacheName: 'api-cache',
		networkTimeoutSeconds: 10,
	}),
);
