spring:
    application:
        name: backend                 # ← 앱 이름

    config:
        import: optional:file:.env[.properties]

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        open-in-view: false
    
    datasource.hikari:
        connection-init-sql: SET NAMES utf8mb4

---
management:
    endpoints:
        web:
            exposure:
                include: health,info

---
jwt:
    secret: ${JWT_SECRET}

---
logging.level:
    show_sql: debug
    org.hibernate.type: trace

---
cloud:
    aws:
        region: ap-northeast-2
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
        sqs:
            url: https://sqs.ap-northeast-2.amazonaws.com/273354621375/ai-processing.fifo
            queue-name: ai-processing.fifo
        s3:
            bucket: ai-processing-output
            path:
                profile: profile
                coordination: coordination
        stack:
            auto: false
