spring:
    application:
        name: backend                 # ← 앱 이름

    config:
        import: optional:file:.env[.properties]

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                jdbc.time_zone: Asia/Seoul
        open-in-view: false
    
    datasource.hikari:
        connection-init-sql: SET NAMES utf8mb4

    jackson:
        time-zone: Asia/Seoul

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB

---
management:
    endpoints:
        web:
            exposure:
                include: health,info

---
jwt:
    secret: ${JWT_SECRET}

---
logging:
    level:
        root: INFO
        com.ssafy.sharedress.config: DEBUG
        com.ssafy.sharedress.adapter: INFO
        com.ssafy.sharedress.application: INFO
        org.springframework.web: INFO

---
cloud:
    aws:
        region: ap-northeast-2
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_SECRET_KEY}
        sqs:
            url: https://sqs.ap-northeast-2.amazonaws.com/273354621375/ai-processing.fifo
            queue-name: ai-processing.fifo
        s3:
            bucket: ai-processing-output
            path:
                profile: profile
                coordination: coordination
                photo: photo
        stack:
            auto: false

---
firebase:
    type: ${FIREBASE_TYPE}
    project_id: ${FIREBASE_PROJECT_ID}
    private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
    private_key: ${FIREBASE_PRIVATE_KEY}
    client_email: ${FIREBASE_CLIENT_EMAIL}
    client_id: ${FIREBASE_CLIENT_ID}
    auth_uri: ${FIREBASE_AUTH_URI}
    token_uri: ${FIREBASE_TOKEN_URI}
    auth_provider_x509_cert_url: ${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
    client_x509_cert_url: ${FIREBASE_CLIENT_X509_CERT_URL}
    universe_domain: ${FIREBASE_UNIVERSE_DOMAIN}
