spring:
    config:
        import: optional:file:.env[.properties]

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        open-in-view: false
    
    datasource.hikari:
        connection-init-sql: SET NAMES utf8mb4

logging.level:
    show_sql: debug
    org.hibernate.type: trace
